Initial dumb substitution of TF->KOPS, tf->kops, terraform->kops, Terraform->Kops

diff --git a/libexec/helpers b/libexec/helpers
--- a/libexec/helpers
+++ b/libexec/helpers
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 
 function error_and_die() {
-  echo -e "tfenv: $(basename ${0}): \033[0;31m[ERROR] ${1}\033[0;39m" >&2
+  echo -e "kopsenv: $(basename ${0}): \033[0;31m[ERROR] ${1}\033[0;39m" >&2
   exit 1
 }
 
 function warn_and_continue() {
-  echo -e "tfenv: $(basename ${0}): \033[0;33m[WARN] ${1}\033[0;39m" >&2
+  echo -e "kopsenv: $(basename ${0}): \033[0;33m[WARN] ${1}\033[0;39m" >&2
 }
 
 function info() {
@@ -23,4 +23,31 @@ function curlw () {
   fi
 
   curl ${TLS_OPT} "$@"
+}
+
+function jq() {
+  if ! which jq 2>&1 >/dev/null; then
+  if -x $(basename ${0})/jq
+    local arch=${KOPSENV_ARCH:-amd64}
+   case "$(uname -s)" in
+  Darwin*)
+    os="darwin_${KOPSENV_ARCH}"
+    ;;
+  MINGW64*)
+    os="windows_${KOPSENV_ARCH}"
+    ;;
+  MSYS_NT*)
+    os="windows_${KOPSENV_ARCH}"
+    ;;
+  CYGWIN_NT*)
+    os="windows_${KOPSENV_ARCH}"
+    ;;
+  *)
+    os="linux_${KOPSENV_ARCH}"
+    ;;
+esac
+
+    jq "$@"
+  fi
+  jq "$@"
 }
diff --git a/libexec/kopsenv-min-required b/libexec/kopsenv-min-required
--- a/libexec/kopsenv-min-required
+++ b/libexec/kopsenv-min-required
@@ -1,17 +1,17 @@
 #!/usr/bin/env bash
-# Usage: tfenv min-required
-# Summary: Detect the minimal required version from *tf files
+# Usage: kopsenv min-required
+# Summary: Detect the minimal required version from *kops files
 set -e
-[ -n "${TFENV_DEBUG}" ] && set -x
+[ -n "${KOPSENV_DEBUG}" ] && set -x
 
 bailout() {
-    >&2 echo "Error: Could not determine required_version based on your terraform sources.
-Make sure at least one of your *tf files includes a required version section like
-terraform {
+    >&2 echo "Error: Could not determine required_version based on your kops sources.
+Make sure at least one of your *kops files includes a required version section like
+kops {
   required_version = \">= 0.0.0\"
 }
 
-see https://www.terraform.io/docs/configuration/terraform.html for details
+see https://www.kops.io/docs/configuration/kops.html for details
 
 "
 
@@ -21,7 +21,7 @@ see https://www.terraform.io/docs/configuration/terraform.html for details
 find_min_required() {
     local root="${1}"
 
-    versions=$(grep -h -R required_version --include '*tf' "$root"/* | tr -c -d '0-9. ~=!<>' )
+    versions=$(grep -h -R required_version --include '*kops' "$root"/* | tr -c -d '0-9. ~=!<>' )
 
     if [[ $versions =~ ([~=!<>]{0,2}[[:blank:]]*[0-9]+[0-9.]+)[^0-9]* ]]; then
         found_min_required=${BASH_REMATCH[1]}
@@ -42,4 +42,4 @@ find_min_required() {
     bailout
 }
 
-find_min_required "${TFENV_DIR}"
+find_min_required "${KOPSENV_DIR}"
diff --git a/libexec/kopsenv-use b/libexec/kopsenv-use
--- a/libexec/kopsenv-use
+++ b/libexec/kopsenv-use
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
-[ -n "${TFENV_DEBUG}" ] && set -x
-source ${TFENV_ROOT}/libexec/helpers
+[ -n "${KOPSENV_DEBUG}" ] && set -x
+source ${KOPSENV_ROOT}/libexec/helpers
 
-[ ${#} -ne 1 ] && error_and_die "usage: tfenv use <version>"
+[ ${#} -ne 1 ] && error_and_die "usage: kopsenv use <version>"
 
 declare version_requested version regex
 
@@ -11,7 +11,7 @@ version_requested="${1}"
 
 if [[ "${version_requested}" =~ ^min-required$ ]]; then
   echo "Detecting minimal required version..."
-  found_min_required="$(tfenv-min-required)"
+  found_min_required="$(kopsenv-min-required)"
 
   if [[ $? -eq 0 ]]; then
       echo "Min required version is detected as ${found_min_required}"
@@ -32,24 +32,24 @@ else
   regex="^${version_requested}$"
 fi
 
-[ -d "${TFENV_ROOT}/versions" ] \
-  || error_and_die "No versions of terraform installed. Please install one with: tfenv install"
+[ -d "${KOPSENV_ROOT}/versions" ] \
+  || error_and_die "No versions of kops installed. Please install one with: kopsenv install"
 
-version="$(\ls "${TFENV_ROOT}/versions" \
+version="$(\ls "${KOPSENV_ROOT}/versions" \
   | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
   | grep -e "${regex}" \
   | head -n 1
 )"
 
-[ -n "${version}" ] || error_and_die "No installed versions of terraform matched '${1}'"
+[ -n "${version}" ] || error_and_die "No installed versions of kops matched '${1}'"
 
-target_path=${TFENV_ROOT}/versions/${version}
-[ -f ${target_path}/terraform ] \
-  || error_and_die "Version directory for ${version} is present, but the terraform binary is not! Manual intervention required."
-[ -x ${target_path}/terraform ] \
-  || error_and_die "Version directory for ${version} is present, but the terraform binary is not executable! Manual intervention required. "
+target_path=${KOPSENV_ROOT}/versions/${version}
+[ -f ${target_path}/kops ] \
+  || error_and_die "Version directory for ${version} is present, but the kops binary is not! Manual intervention required."
+[ -x ${target_path}/kops ] \
+  || error_and_die "Version directory for ${version} is present, but the kops binary is not executable! Manual intervention required. "
 
 info "Switching to v${version}"
-echo "${version}" > "$(tfenv-version-file)" || error_and_die "'switch to v${version} failed'"
-terraform --version 1>/dev/null || error_and_die "'terraform --version' failed. Something is seriously wrong"
+echo "${version}" > "$(kopsenv-version-file)" || error_and_die "'switch to v${version} failed'"
+kops --version 1>/dev/null || error_and_die "'kops --version' failed. Something is seriously wrong"
 info "Switching completed"
