Bracketed in if-else

diff --git a/libexec/kopsenv-install b/libexec/kopsenv-install
--- a/libexec/kopsenv-install
+++ b/libexec/kopsenv-install
@@ -33,32 +33,53 @@ version="$(kopsenv-list-remote | grep -e "${regex}" | head -n 1)"
 
 dst_path="${KOPSENV_ROOT}/versions/${version}"
 if [ -f "${dst_path}/kops" ]; then
-  echo "Kops v${version} is already installed"
+  echo "Kops ${version} is already installed"
   exit 0
 fi
 
 # Check if version_requested contains "invoca", and if does, get version from the Invoca Kops fork
 if [[ "${version_requested}" =~ "invoca" ]]; then
-  version_url="https://api.github.com/repos/Invoca/kops/releases/download/${version}"
+  exe_name="kops"
+  version_url="https://github.com/Invoca/kops/releases/download/${version}/${exe_name}"
 else
+exe_name="kops-$(kops_platform)"
   version_url="https://github.com/kubernetes/kops/releases/download/${version}"
 fi
 
-exe_name="kops-$(kops_platform)"
 (( "$?" )) && exit $?
 
-info "Installing Kops v${version}"
+info "Installing Kops ${version}"
 
 # Create a local temporary directory for downloads
 download_tmp="$(mktemp -d kopsenv_download.XXXXXX)" || error_and_die "Unable to create temporary download directory in $(pwd)"
 # Clean it up in case of error
 trap "rm -rf ${download_tmp}" EXIT;
 
+if [[ "${version_requested}" =~ "invoca" ]]; then
+
+  exe_name="kops"
+
+info "Downloading release from ${version_url}"
+curlw -# -f -L -o "${download_tmp}/${exe_name}" "${version_url}" || error_and_die "Download failed"
+
+mkdir -p "${dst_path}" || error_and_die "Failed to make directory ${dst_path}"
+cp "${download_tmp}/${exe_name}" "${dst_path}/kops" || error_and_die "Copy of ${exe_name} from ${download_tmp} to ${dst_path} failed"
+chmod a+x "${dst_path}/kops" || error_and_die "Unable to set execute on ${dst_path}/kops"
+
+
+
+  else
+
 info "Downloading release from ${version_url}/${exe_name}"
 curlw -# -f -L -o "${download_tmp}/${exe_name}" "${version_url}/${exe_name}" || error_and_die "Download failed"
 
 mkdir -p "${dst_path}" || error_and_die "Failed to make directory ${dst_path}"
+tar -cvf "${download_tmp}/${exe_name}"
 cp "${download_tmp}/${exe_name}" "${dst_path}/kops" || error_and_die "Copy of ${exe_name} from ${download_tmp} to ${dst_path} failed"
+
+
+fi
+
 chmod a+x "${dst_path}/kops" || error_and_die "Unable to set execute on ${dst_path}/kops"
 
 info "Installation of kops v${version} successful"
diff --git a/libexec/kopsenv-use b/libexec/kopsenv-use
--- a/libexec/kopsenv-use
+++ b/libexec/kopsenv-use
@@ -14,8 +14,8 @@ if [[ "${version_requested}" =~ ^min-required$ ]]; then
   found_min_required="$(kopsenv-min-required)"
 
   if [[ $? -eq 0 ]]; then
-      echo "Min required version is detected as ${found_min_required}"
-      version_requested=${found_min_required}
+    echo "Min required version is detected as ${found_min_required}"
+    version_requested=${found_min_required}
   else
     exit 1
   fi
@@ -51,5 +51,5 @@ target_path=${KOPSENV_ROOT}/versions/${version}
 
 info "Switching to v${version}"
 echo "${version}" > "$(kopsenv-version-file)" || error_and_die "'switch to v${version} failed'"
-kops version client 1>/dev/null || error_and_die "'kops version client' failed. Something is seriously wrong"
+kops version client 1>/dev/null 2>&1 || error_and_die "'kops version client' failed. Something is seriously wrong"
 info "Switching completed"
