Initial development

diff --git a/libexec/kopsenv-install b/libexec/kopsenv-install
--- a/libexec/kopsenv-install
+++ b/libexec/kopsenv-install
@@ -16,18 +16,6 @@ else
   version_requested="${1}"
 fi
 
-if [[ "${version_requested}" =~ ^min-required$ ]]; then
-  echo "Detecting minimal required version..."
-  found_min_required="$(kopsenv-min-required)"
-
-  if [[ $? -eq 0 ]]; then
-      echo "Min required version is detected as ${found_min_required}"
-      version_requested=${found_min_required}
-  else
-    exit 1
-  fi
-fi
-
 if [[ "${version_requested}" =~ ^latest\:.*$ ]]; then
   version="${version_requested%%\:*}"
   regex="${version_requested##*\:}"
@@ -49,31 +37,9 @@ if [ -f "${dst_path}/kops" ]; then
   exit 0
 fi
 
-KOPSENV_ARCH=${KOPSENV_ARCH:-amd64}
-case "$(uname -s)" in
-  Darwin*)
-    os="darwin_${KOPSENV_ARCH}"
-    ;;
-  MINGW64*)
-    os="windows_${KOPSENV_ARCH}"
-    ;;
-  MSYS_NT*)
-    os="windows_${KOPSENV_ARCH}"
-    ;;
-  CYGWIN_NT*)
-    os="windows_${KOPSENV_ARCH}"
-    ;;
-  *)
-    os="linux_${KOPSENV_ARCH}"
-    ;;
-esac
-
-keybase_bin="$(which keybase 2>/dev/null)"
-shasum_bin="$(which shasum 2>/dev/null)"
-
-version_url="https://releases.hashicorp.com/kops/${version}"
-tarball_name="kops_${version}_${os}.zip"
-shasums_name="kops_${version}_SHA256SUMS"
+version_url="https://github.com/kubernetes/kops/releases/download/${version}"
+exe_name="kops-$(kops_platform)"
+(( "$?" )) && exit $?
 
 info "Installing Kops v${version}"
 
@@ -82,42 +48,13 @@ download_tmp="$(mktemp -d kopsenv_download.XXXXXX)" || error_and_die "Unable to 
 # Clean it up in case of error
 trap "rm -rf ${download_tmp}" EXIT;
 
-info "Downloading release tarball from ${version_url}/${tarball_name}"
-curlw -# -f -o "${download_tmp}/${tarball_name}" "${version_url}/${tarball_name}" || error_and_die "Tarball download failed"
-info "Downloading SHA hash file from ${version_url}/${shasums_name}"
-curlw -s -f -o "${download_tmp}/${shasums_name}" "${version_url}/${shasums_name}" || error_and_die "SHA256 hashes download failed"
-
-# Verify signature if keybase is present.
-if [[ -n "${keybase_bin}" && -x "${keybase_bin}" ]]; then
-  "${keybase_bin}" status | grep -Eq '^Logged in:[[:space:]]*yes'
-  keybase_logged_in=$?
-  "${keybase_bin}" list-following | grep -Fq hashicorp
-  keybase_following_hc=$?
-
-  if [[ "${keybase_logged_in}" -ne 0 || "${keybase_following_hc}" -ne 0 ]]; then
-    warn_and_continue "Unable to verify GPG signature unless logged into keybase and following hashicorp"
-  else
-    info "Downloading SHA hash signature file from ${version_url}/${shasums_name}.sig"
-    curlw -s -f -o "${download_tmp}/${shasums_name}.sig" "${version_url}/${shasums_name}.sig" || error_and_die "SHA256SUMS signature download failed"
-    "${keybase_bin}" pgp verify -S hashicorp -d "${download_tmp}/${shasums_name}.sig" -i "${download_tmp}/${shasums_name}" || error_and_die "SHA256SUMS signature does not match!"
-  fi
-else
-  # Warning about this avoids an unwarranted sense of confidence in the SHA check
-  warn_and_continue "No keybase install found, skipping GPG signature verification"
-fi
-
-if [[ -n "${shasum_bin}" && -x "${shasum_bin}" ]]; then
-  (
-    cd "${download_tmp}"
-    "${shasum_bin}" -a 256 -s -c <(grep -F "${tarball_name}" "${shasums_name}") || error_and_die "SHA256 hash does not match!"
-  )
-else
-  # Lack of shasum deserves a proper warning
-  warn_and_continue "No shasum tool available. Skipping SHA256 hash validation"
-fi
+info "Downloading release from ${version_url}/${exe_name}"
+curlw -# -f -L -o "${download_tmp}/${exe_name}" "${version_url}/${exe_name}" || error_and_die "Download failed"
 
 mkdir -p "${dst_path}" || error_and_die "Failed to make directory ${dst_path}"
-unzip "${download_tmp}/${tarball_name}" -d "${dst_path}" || error_and_die "Tarball unzip failed"
+cp "${download_tmp}/${exe_name}" "${dst_path}/kops" || error_and_die "Copy of ${exe_name} from ${download_tmp} to ${dst_path} failed"
+chmod a+x "${dst_path}/kops" || error_and_die "Unable to set execute on ${dst_path}/kops"
 
 info "Installation of kops v${version} successful"
 kopsenv-use "$version"
+
